/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ayakaji_network_prism_Native */

#ifndef _Included_org_ayakaji_network_prism_Native
#define _Included_org_ayakaji_network_prism_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ayakaji_network_prism_Native
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ayakaji_network_prism_Native_say
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
